name: Feature request
description: Suggest an idea to improve the package
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea. Please describe the problem and proposed solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
